apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-7pnu
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0054-tenant/tkrw-pr712-0075-0054-app/devfile-sample-7pnu@sha256:1548914886d69abd37151c9ebd21106b5bd57ff27b4c44bc8be881747ef003b8
        name: my-nodejs
        resources: {}
status: {}
